### PR TITLE
Rename info.json to dashjojo1

### PR DESCRIPTION
**Pull request by DamianWilliams1122**
4AEE18F160481e7f2364cf2feb25deb8d9feff52be1ab8883AFDEB23

### CODE REVIEW

**Review by DamianWilliams1122 — COMMENTED** [review]
REVIEWED ALL CHANGES

**Review by DamianWilliams1122 — COMMENTED** [review]
REVIEW REREAD

**Review by DamianWilliams1122 — COMMENTED** [review]
REVIEWED CHA NGES

**Comment by VictorZhang2014** [comment]
Hi @DamianWilliams1122  what valid info did you provide? This is not a token info

**Pull request closed without merging**
